name: fast_ctd
channels:
  - conda-forge

# NOTE: cmake and occt are the only dependencies you need to build the project.

dependencies:
  - python >=3.11,<3.12
  - openmc=0.15.0=dagmc_*
  - cmake
  # tracks FreeCAD version
  - occt=7.8.1=all_*
  - pip
  - pip:
      - -e ../[dev]
